#
# Awesome App Landing Page Config
#

# Be sure all REQUIRED fields are filled out!

baseurl: "/crunch/"
production_url: https://avniel.app/crunch/
base_path: https://avniel.app/crunch/

url: https://avniel.app/crunch/

#
# General App Info
#
app:
  name: ¢runch # REQUIRED - Enter your app name
  ios_id: 1440358478 # REQUIRED - 10 Digit Numeric App ID (lookup in iTunes Connect)
  android_id: app.crunch # Optional - Enter Android app id like: com.example.app

  icon: images/icon.png # Leave blank to auto-magically populate
  # To update use path relative to project root with no leading slash:
  # e.g. images/app-icon-512.png
  # 512px or greater, square

  #favicon: # uncomment if uploading own favicon
  # To update use path relative to project root with no leading slash:
  # e.g. images/app-favicon.png - can be .ico or .png
  # 16px or greater, square

  screenshot: images/app-screen-640x1136.png # Leave blank to auto-magically populate
  # To update use path relative to project root with no leading slash:
  # e.g. images/app-screen-640x1136.png
  # 640x1136px

  #video: # uncomment if prefer to show a video preview in the screen instead of image
  # To update use path relative to project root with no leading slash:
  # e.g. images/app-preview.mp4
  # 640x1136px

  #app_twitter: # uncomment if the app has a twitter account "@my-awesome-app"
  #creator_twitter: # uncomment if creator has a twitter account "@awesome-dev"
  social_image: images/app-screen-640x1136_iphone6splusrosegold_portrait.png # uncomment and add an image - defaults to icon
  # This will show up when your url is shared on sites like facebook and twitter
  # To update use path relative to project root with no leading slash:
  # e.g. images/app-social_image.png
  # 512px or greater, square or width = 2X height
#
# Marketing
#
marketing_header: Free your grocery budget # Optional
marketing_desc: Almond milk $2 off&mdash;sweet deal right? Think again, it’s a terrible deal for your budget. <span class="crunch">&cent;runch</span> rates almond milk D grade food because you'd have to pay $13 to get a meal's worth of calories<br><br>What is a better deal? Whole milk! It provides a meal's worth of calories for only $0.90<br><br>Slash your grocery bill and join the movement. <span class="crunch">&cent;runch</span> was inspired by the <a href="http://www.mrmoneymustache.com/2012/03/29/killing-your-1000-grocery-bill/">Mr Money Mustache</a> blog</a>

#
# Social Links
#
# Includes an icon for each username you enter
#
social-links:
  github:
  facebook: avnielapps
  twitter: avnielapps
  pinterest:
  instagram:
  email:
  youtube: # channel/<your_long_string> or <user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/

#
# Enable/Disable Features & Page Elements
#
enable:
  app_icon: true
  smart_app_banner: true

#
# Device
#
# Available devices:
# * iphone-se-silver-vertical
# * iphone-se-space-gray-vertical
# * ipod-touch-blue-vertical
#
device: iphone-se-silver-vertical # REQUIRED

#
# Theme Settings
#
background_color: "#989898" # Optional
background_image: /images/backgrounds/crunch-splash.jpg # Optional - Use Relative path e.g. images/backgrounds/image.jpg
text_color: white # Optional
link_color: "#FAA" # Optional
social_link_color: white # Optional
download_button_background_color: "#F53E45" #"#0191FF" # Optional
download_button_text_color: white; # Optional

#
# Site Info
#
# If you want specific meta info for your <head></head> tags
#
title: ¢runch # Optional - Enter your site title
description: # Optional - Enter your site description

#
# Google Analytics
#
google_analytics: # Enter your tracking code (e.g. UA-2110908-2) to activate tracking

#
# iTunes Affiliate Program
#
# Sign up here: http://www.apple.com/itunes/affiliates/
#
# Disclaimer:
# This will default to using the author's affiliate token if left blank
#
itunes_affiliate_token: # Optional

#
# !! You don't need to change any of the configuration flags below !!
#

# The release of Awesome App Landing Page that you're using
version: v1.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
